---
- name: Sync RHEL repositories from the CDN
  hosts: localhost
  vars:
    product:
    repo_list: 
    organization: 
  become: false

  tasks:
    - name: "Sync repositories"
      redhat.satellite.repository_sync:
        username: '{{ username }}'
        password: '{{ password }}'
        server_url: '{{ server_url }}'
        repository: "{{ item }}"
        product: "{{ product }}"
        organization: "{{ organization }}"
      loop: "{{ repo_list }}"